version: '2'
 
services:
  mysql:
    image: mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
      MYSQL_ROOT_HOST: "%"
    volumes:  
      - ~/.docker_data/exampleapp:/var/lib/mysql
  mytestapp:
    image: testapp
    ports:
      - 8080:8080
    environment:
      DB_USER: "root"
      DB_PASS: "mypassword"
      DB_HOST: "mysql"
  




